/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CadastroUser: typeof import('./src/components/CadastroUser.vue')['default']
    CardComProps: typeof import('./src/components/CardComProps.vue')['default']
    CardGrid: typeof import('./src/components/CardGrid.vue')['default']
    CardTeste: typeof import('./src/components/CardTeste.vue')['default']
    CardVcard: typeof import('./src/components/CardVcard.vue')['default']
    CardWindows: typeof import('./src/components/CardWindows.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestItemGroup: typeof import('./src/components/TestItemGroup.vue')['default']
    UsersTable: typeof import('./src/components/UsersTable.vue')['default']
  }
}
